---
# tasks file for consul-config
- name: install packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - python-pip
- name: install pip packages
  pip:
    name: "{{ item }}"
    state: present
  with_items:
    - awscli
- debug:
    var: "ec2_tag_Name"
- name: copies over consul configs
  synchronize:
    src: "templates/consul/{{ ec2_tag_Name }}/"
    dest: "/etc/consul.d"
    mode: push
    delete: true
    recursive: true
    compress: true
  notify:
    - restart consul
