---
# tasks file for consul-config
- name: register instance id
  command: "ec2metadata --instance-id"
  register: instance_id
- name: register region
  shell: curl -s http://169.254.169.254/latest/dynamic/instance-identity/document | grep region | awk -F\" '{print $4}'
  register: region
- name: register tag value
  shell: "/usr/local/bin/aws ec2 describe-tags --filters 'Name=resource-id,Values={{            instance_id.stdout }}' 'Name=key,Values=Name' --region={{ region.stdout }} --output=text | cut -f5"
  register: name_tag
- name: copies over consul configs
  synchronize:
    src: "files/consul/{{ name_tag.stdout }}/"
    dest: "/etc/consul.d"
    mode: push
    delete: true
    recursive: true
    compress: true
  notify:
    - restart consul
